conf:
  data:
    test_size: 0.25
    n_classes: 50
    batch_size: 64
    val_size: 0.25
    dataloader_num_workers: 8
    test_dir: data/test
    train_dir: data/train
  model:
    name: microsoft/resnet-18
    weights: ResNet18_Weights
    pretrained: true
    layers: 5
    output_dim: 128
    save_model: dog_model.ckpt
  train:
    epochs: 1
    learning_rate: 0.001
    weight_decay: 0.01
    step_size: 3
    gamma: 0.1
    model_dir: dog_model
    accelerator: cuda
    precision: 16-mixed
    devices:
      - 0
    grad_accum_steps: 4
    overfit_batches: 0
    num_sanity_val_steps: 4
    val_check_interval: 1.0
    full_deterministic_mode: false
    benchmark: false
    gradient_clip_val: 1.0
    profiler: null
    log_every_n_steps: 10
    detect_anomaly: false
    batch_size_finder: false
  artifacts:
    experiment_name: experiment
    checkpoint:
      use: false
      dirpath: checkpoints
      filename: "{experiment_name}_{epoch:02d}-{val_loss:.4f}"
      monitor:
        - val_loss
        - val_accuracy
      save_top_k: 3
      every_n_train_steps: null
      every_n_epochs: 1
  callbacks:
    model_summary:
      max_depth: 1
    swa:
      use: false
      lrs: 0.001
  csv:
    csv_dir: Dogs_predictions.csv
cfg:
  data:
    test_size: 0.25
    n_classes: 50
    batch_size: 64
    val_size: 0.25
    dataloader_num_workers: 8
    test_dir: data/test
    train_dir: data/train
  model:
    name: microsoft/resnet-18
    weights: ResNet18_Weights
    pretrained: true
    layers: 5
    output_dim: 128
    save_model: dog_model.ckpt
  train:
    epochs: 1
    learning_rate: 0.001
    weight_decay: 0.01
    step_size: 3
    gamma: 0.1
    model_dir: dog_model
    accelerator: cuda
    precision: 16-mixed
    devices:
      - 0
    grad_accum_steps: 4
    overfit_batches: 0
    num_sanity_val_steps: 4
    val_check_interval: 1.0
    full_deterministic_mode: false
    benchmark: false
    gradient_clip_val: 1.0
    profiler: null
    log_every_n_steps: 10
    detect_anomaly: false
    batch_size_finder: false
  artifacts:
    experiment_name: experiment
    checkpoint:
      use: false
      dirpath: checkpoints
      filename: "{experiment_name}_{epoch:02d}-{val_loss:.4f}"
      monitor:
        - val_loss
        - val_accuracy
      save_top_k: 3
      every_n_train_steps: null
      every_n_epochs: 1
  callbacks:
    model_summary:
      max_depth: 1
    swa:
      use: false
      lrs: 0.001
  csv:
    csv_dir: Dogs_predictions.csv
